[workspace]
resolver = "2"
members = ["day-1", "day-2", "day-3", "day-4", "day-5", "day-6", "day-7", "day-8", "day-9"]

[workspace.dependencies]
crossbeam-channel = "0.5.13"
lazy_static = "1.5.0"
regex = "1.11.1"
